site_name: Tarea 2

theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Inicio: index.md
  - Explicación: explanation.md
  - Referencias: reference.md

